---
Name: versionedgridrows
---
SilverStripe\Forms\GridField\GridField:
  extensions:
    - NathanCox\VersionedGridRows\VersionedGridRowsExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - versionedgridrows/css/versionedgridrows.css
